# Server configuration
[server]
host = "0.0.0.0"
port = 8080
cors_allowed_origins = ["http://localhost:8100"]

# Bible API configuration
[bible]
base_url = "https://alkitab.mobi"
default_version = "tb" 