# Server configuration
[server]
port = 8080
cors_allowed_origins = ["http://localhost:8100", "http://localhost:3000"]

# Bible API configuration
[bible]
base_url = "https://alkitab.mobi"
default_version = "tb" 