name: Rust CI/CD

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: 🧪 Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Run Tests
      run: cargo test --verbose

  deploy:
    name: 🚀 Deploy to Shuttle
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Shuttle CLI
      run: cargo install cargo-shuttle

    - name: Authenticate with Shuttle
      run: shuttle login --api-key ${{ secrets.SHUTTLE_API_KEY }}

    - name: Deploy
      run: shuttle deploy --no-follow
